/** @format */

const userActionsTypes = {
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	SIGN_OUT: 'SIGN_OUT',
	GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
	GOOGLE_SIGN_IN_SUCCESS: 'GOOGLE_SIGN_IN_SUCCESS',
	GOOGLE_SIGN_IN_FAIL: 'GOOGLE_SIGN_IN_FAIL',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	EMAIL_SIGN_IN_SUCCESS: 'EMAIL_SIGN_IN_SUCCESS',
	EMAIL_SIGN_IN_FAIL: 'EMAIL_SIGN_IN_FAIL',
	CHECK_USER: 'CHECK_USER',
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
};

export default userActionsTypes;
